import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const [rawId, ...args] = process.argv.slice(2);
if (!rawId || rawId === '--help') {
  console.log('Usage: node scripts/create-layer.mjs <kebab-id> --label "Label" --source "Source" --url https://example.org/feed');
  process.exit(rawId ? 0 : 1);
}

const id = rawId.toLowerCase();
if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id)) throw new Error('Layer id must be kebab-case.');

function option(name, fallback = '') {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] || fallback : fallback;
}

const label = option('--label', id.replace(/-/g, ' '));
const source = option('--source', 'Documented public source');
const sourceUrl = option('--url', 'https://example.org/feed');
const color = option('--color', '#3FB6FF');
const target = path.join(root, 'assets', 'layers', `${id}.js`);
if (fs.existsSync(target)) throw new Error(`Layer already exists: assets/layers/${id}.js`);

const content = `/**
 * Layer: ${label}
 * Generated by scripts/create-layer.mjs. Replace the fetcher with a documented,
 * rate-aware adapter and keep source provenance attached to every point.
 */

Overview.registerLayer({
  id: '${id}',
  label: '${label.replaceAll("'", "\\'")}',
  source: '${source.replaceAll("'", "\\'")}',
  sourceUrl: '${sourceUrl.replaceAll("'", "\\'")}',
  color: '${color}',
  defaultOn: false,
  refreshMs: 5 * 60 * 1000,

  async fetchPoints() {
    const response = await OverviewSources.json('${sourceUrl.replaceAll("'", "\\'")}');
    const points = (response.data?.points || []).map(point => ({
      id: point.id,
      lat: Number(point.lat),
      lon: Number(point.lon),
      size: Number(point.size) || 3,
      label: point.label || point.name || point.id || '${label.replaceAll("'", "\\'")}'
    }));
    return { points, source: '${source.replaceAll("'", "\\'")}' };
  }
});
`;

fs.writeFileSync(target, content);
console.log(`Created assets/layers/${id}.js. Add its script tag to index.html, registry metadata, docs, and tests.`);
